ARG VARIANT="3.10-bullseye"
FROM napptive/playground:latest as playgrond

FROM mcr.microsoft.com/vscode/devcontainers/python:${VARIANT}
WORKDIR  /app
COPY --from=playgrond /app /app
ENV PATH=$PATH:/app/
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]